### ISSUE TITLE
Idea for easy antialiasing using bidirectional filter

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#123]
Hey robin, how many samples of delay do we need to apply bidirectional filtering in realtime?

What if we had, say, a 4 sample delay.

My idea is: Somehow, when a discontinuity is detected, apply a simple bidirectional filter just for that area of discontinuity. I can't think much beyond this, can you tell me if this is "deceptively simple" or actually a good idea?

Ultimately, I'd like to eventually have a polynomial-like antialiasing of waveforms that could be applied to arbitrary signals. I figured a conditional bidirectional filter might be a solution.

**Comment by RobinSchmidt** [comment]
hmm...bidirectional filtering with an IIR filter in realtime is actually not really possible because strictly speaking, you would have to look infinitely long into the future. maybe it can be approximated. you would have to look as long into the future (i.e. apply as much delay) as long the filter needs to ring out (which, again strictly speaking, takes an infinite amount of time)

**Comment by elanhickler** [comment]
will close, start a polyblep discussion in the future.
