### ISSUE TITLE
any idea why comments widget doesn't show in chaosfly?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#152]
just stopped working. No idea why. Checked the debugger, looks good. Not sure how to debug further.

**Comment by RobinSchmidt** [comment]
for some reason, the line:
`addWidget(editorComments);`
was missing. i added it. did you perhaps accidently delete it? i also updated your myparams to call get/setNormalizedValue instead of get/setProportionlaValue (i renamed the method) ...you may have to drag a library update or revert that

btw. do you have a special reason to set the "Platform Toolset" setting to v140_xp in your jucer file? i laways have to set that temporarily back to "default" in order to get it compile here (because apparently i don't have that toolset installed)

**Comment by RobinSchmidt** [comment]
seems like you deleted it in your commit on 30. Dec (with message "chaosfly works again")

**Comment by elanhickler** [comment]
lol i deleted it by mistake then.

platform toolset v140_xp is for making it compatible with windows XP
