### ISSUE TITLE
issue setting name of slider, undoing name already set

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#155]
![image](https://user-images.githubusercontent.com/9116575/34634957-a5e091fc-f246-11e7-86dd-0b1bdb37f254.png)

I set slider display name earlier in the code by calling setSliderName, but this overwrites it.

This seems to be the slider xml name. This is confusing because I don't know where in your library you use name for xml and where you use name for display so I don't know how to solve this.

**Comment by elanhickler** [comment]
i better override the slider paint method and create my own slider.

**Comment by RobinSchmidt** [comment]
oh! why do i actually set the slider name there? this seems to make no sense to me right now. maybe i should just delete that line (or comment it out first and delete later). the xml uses the Parameter's name only, the slider name is irrelevant for the xml.

aahhh...perhaps i should move the setSliderName into RSlider::assignParameter - so that assigning a parameter takes over the parameter's name, but can later be changed. i guess, that was my intention. i think, i'll just try it and if it doesn't break anything, keep it

**Comment by RobinSchmidt** [comment]
ok, done. now the slider will take over the parameter's name when the parameter gets assigned. when you want to have the slider to display something that is different from the parameter's name, you can call setSliderName after assigning the parameter to overwrite it. as said - the xml storing/recalling does not care at all about the slider's name - it uses the parameter's name

**Comment by RobinSchmidt** [comment]
> i better create my own slider class and override the slider paint method. I need to start overriding all your paint methods anyway.

hmm...yeaahh...you could do this....but i guess, i should better get serious about delegating widget painting to painter objects soon. this is the much more flexible solution because then you don't have to choose which slider subclass you want to override (there are a ModulatableSlider, AutomatableSlider subclasses who have all slightly different behavior -  and who know what else we need in the future). and you could use my ready made (sub)module editors, like the breakpoint, eq, etc. editor with your slider painting

**Comment by elanhickler** [comment]
I overrode your slider paint method already, there's a few things that aren't quite right about the painting that I've been wanting to fix anyway, such as not displaying the right default value tick mark or whatever.

**Comment by RobinSchmidt** [comment]
>  not displaying the right default value tick mark

i only noticed this recently after introducing the mapper - which is one of the things i need to fix. are you saying, it was showing wrong tick-marks already before having a mapper?

**Comment by elanhickler** [comment]
it's always been wrong because you were assuming things in your code, such as the default value being the tick value, when tick vs default could be different, such as bipolar amplitude default of 1, but tick should be 0.

**Comment by elanhickler** [comment]
so, for the painting of the breakpoint can do you stuff like

"use this painter for dots"

"use this painter for lines"

"use this painter for background"

or something, so we can customize all of it completely

**Comment by RobinSchmidt** [comment]
i was actually more talking about painter objects for widgets - like mySlider->setPainter(myPainter) - and the same for buttons, menus, etc.. this would work also for also whole editors, i think - but for the plots...hmmm...i must think about it. i don't really like having  painter objects for lines, dots, background, etc. - but perhaps i could have a painter object for the whole plot

**Comment by RobinSchmidt** [comment]
a SliderPainter (sub)class would have a very simple interface: just one function
` paintSlider(Graphics&g, Slider* s)`
and then you could implement/override that. maybe for plots, it would have a more complex interface with functions like paintBackground, paintGraph, etc. ...that's something i need to think about

**Comment by elanhickler** [comment]
well for now, maybe changing line thickness, dot size, and color for various things is enough. My main concern right now is the breakpoint envelope modulator for FMD.

**Comment by RobinSchmidt** [comment]
this is not so easy because the plot-editor is a sub-object (or "child-component") of the whole envelope editor

**Comment by elanhickler** [comment]
closing
