### ISSUE TITLE
removing prettyscope crashes REAPER

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#156]
![image](https://user-images.githubusercontent.com/9116575/34644531-915c005e-f2f5-11e7-8bbe-057f20565a25.png)
  
Actually, just build standalone version and close it. Same issue.

**Comment by RobinSchmidt** [comment]
i added an dummy implementation for the debugger of "myparams". now you can look at the variables in the crash. i happens when a Keytracking parameter gets destroyed - the "menuItems" array has an insane size and is fill of invalid pointers

**Comment by RobinSchmidt** [comment]
maybe you have a problem with initializing this stuff?

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/34653125-ad3b4078-f3a4-11e7-9e3d-0ad19c338e92.png)

I set menuItems to something specific. Now I can't hit the destructor, I get this crash:

![image](https://user-images.githubusercontent.com/9116575/34653132-c291c7c6-f3a4-11e7-88b6-bac323cff6b1.png)

So... there's something really ****ed up going on. I'll have to walk back to an older version of RS-MET until I no longer get these issues. Btw, these issues only showed up recently while I haven't made functional changes to myparams.

**Comment by RobinSchmidt** [comment]
wtf is going on? maybe try jumping back before i implemented this repaintOnMessageThread function. i think, this is only place where i create an AsyncCallInvoker (indirectly, the `callAsync` call there creates one), so it could be related to the other (memory leak) bug. i actually doubt that this one here is my bug but who knows.

**Comment by RobinSchmidt** [comment]
or maybe just comment out that callAsync branch. obviously, some repaints will not work anymore but maybe we can see if it fixes any crash or memory leak

**Comment by RobinSchmidt** [comment]
i think, this version is the last before i implemented repaintOnMessageThread:
76e645630c186d8f5500bf80777e6290fa630399
at 27. Dec

**Comment by RobinSchmidt** [comment]
can't build pretty scope anymore - i suppose it's because you reverted to an older version of my library. however - one of the compilation errors jumped into my face:
```
double y = valueToProportionOfLength(RSlider::valueOnMouseDown);  // in 0..1
//double y = valueToProportionOfLength(RSlider::normalizedValueOnMouseDown);  // in 0..1
```
to the commented normalizedValueOnMouseDown you should *not* apply valueToProportionOfLength function. the `normalizedValue` already *is* the proportion of length, i.e. the value between 0..1. maybe that explains messed up sliders?

**Comment by RobinSchmidt** [comment]
...maybe we are getting closer - as i said in the thread about macro controllers: widgets should *not* call Parameter::setValue directly anymore. they should now call setNormalizedValue. ...because otherwise i can't support nonmonotonic mapping functions - and even monotonic ones would be a mess to implement

**Comment by RobinSchmidt** [comment]
i did not protect that function because in the baseclass Parameter there actually is no problem with calling setValue directly. the problem only arises in subclass MetaControlledParameter. maybe i should protect it there. ...later maybe also in SmoothableParameter (it's in between parameter and meta-controlled in the class hierarchy) ....when we want to fix the smoothing problem (the problem with smoothing actual values instead of normalized values)

**Comment by elanhickler** [comment]
im on the latest build and it looks like the crash is due to adding child modules. that's all I know so far.

**Comment by elanhickler** [comment]
close
