### ISSUE TITLE
when resetting slider, possibly due to smoothing, value does not display target value

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#163]
slider will display some number other than 0 (assuming 0 is the default value after reset)

**Comment by elanhickler** [comment]
things get even more wacky when typing in a number and pressing enter

**Comment by RobinSchmidt** [comment]
ooh...yes - i can see this in toolchain, too - the slider itself is at the correct position but the numeric readout value is wrong. yes - this has to do with smoothing - when setting smoothing to zero, it works correctly. i will look into this

**Comment by RobinSchmidt** [comment]
this is new since the mapper was introduced, right? i think, i need to adapt the SmoothableParameter class also to use only setNormalizedValue and not setValue anymore. it's in between Parameter and MetaControlledParameter in the class hierarchy. then we should also have more proper smoothing behavior with regard to up/down speed, etc.

**Comment by elanhickler** [comment]
ive noticed this kind of glitch before the mapper, maybe it's more noticeable now

**Comment by RobinSchmidt** [comment]
it's currently all a bit messed up due to the various different values (raw/mapped, smoothed/target, modulated/unmodulated)... i think, i need to clean up the code and exactly clarify what is what i which circumstances. for example Parameter::callValueChangeCallbacks calls the callbacks with whatever value Parameter::value currently has which implies Parameter::value must reflect the final value after everything (smoothing, modulation, mapping) has been applied...but this is then inappropriate as return value for getValue when a slider calls it... i need to seriously clean up this mess

**Comment by elanhickler** [comment]
no longer relevant
