### ISSUE TITLE
Need to notify OpenGLCanvas from PrettyScopeModule

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#166]
I need to run this code:
OpenGLCanvas.cpp: `void OpenGLCanvas::initializeParamLookup()`
![image](https://user-images.githubusercontent.com/9116575/34806759-36bba29e-f642-11e7-94bd-42efab9a9ed7.png)

with this
PrettyScopeModule.cpp: `void PrettyScopeModule::setupCallbacks()`
![image](https://user-images.githubusercontent.com/9116575/34806781-4eef90be-f642-11e7-859a-0f47b37ad933.png)

because I want to modulate the clear button, we we can do rhythmic clearing of the canvas for example.

**Comment by RobinSchmidt** [comment]
oh - and the problem is that the "clear" parameter is part of the audio-module and the canvas is part of the gui? yeah, you can not just call callbacks on gui objects the same way you call them on audio dsp objects. the juce doc itself says that that audio-code should not keep references to the editor...although, if you are really careful to clear any references on destruction of the gui, it may work. in this case, i qould probably just move that isClearingCanvas falg into the audiomodule (or introduce a corresponding flag there), set it true in the parameter-callback, check it in the rendering code and set it back to false after clearing was done. ....just my first idea

**Comment by elanhickler** [comment]
solved using some bools in Module that Canvas reads and writes.

if clearCanvas value goes above 0.5, doClearCanvas is set to true, and canvasWasCleared is set to true after canvas was cleared. canvasWasCleared is set to false only after clearCanvas value is below 0.5 again, so it only clears once for passing the 0.5 threshold.

but then I also need an RButton listener to to toggle clear canvas when user presses button otherwise modulation might bring value of button below 0, and then clicking the button may cause the value to not reach 0.5 (because modulation value is combined with current button value). 

The only problem now is that the GUI button is a toggle instead of a push. I mean, it needs to turn off on mouseDown. I added AutomatableClickButton and will create a pull request.

oh, these aren't turning red when adding modulation connections...

ok just added more modulatable classes

**Comment by RobinSchmidt** [comment]
>  I added AutomatableClickButton and will create a pull request.

hmm...i'm not really convinced that i want that. maybe keep it in your framework for the time being. i need to think about that

**Comment by elanhickler** [comment]
It's a big hassle if I make a pull request and you don't accept it. Now you can't debug my projects easily because my RS-MET will be different form yours. Well, if you know how to hop on to different forks quickly, it would be fairly simple to switch to my version of RS-MET temporarily and then switch back to yours.

I better not do pull requests.

**Comment by RobinSchmidt** [comment]
it depends. if it is an addition that is only useful in your context *and* you can do it in your framework, then maybe better add it there
