### ISSUE TITLE
Need to show/hide controls based on combo box

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#17]
I am trying to create a combo box with 3 options.

I am going to place 3 sliders on the exact same spot on the UI.

I need to show/hide the right slider based on the combo box.

How do I do it?

I already tried `->setVisible(false);` but I get access violation because the slider doesn't exist when the function is called or something.

**Comment by RobinSchmidt** [comment]
yes, the normal way would be indeed to call setVisible(false) inside the comboBoxChanged callback and with "true" for the selected one of them (or in some function that is called from the callback - i like to write functions like "updateSliderVisibility" and call it from the callback.). when are the sliders created? maybe the callback gets called before they are created? i can only guess here

**Comment by elanhickler** [comment]
Spiral Generator is setup like Chaosfly. i.e. you don't have to guess! You coded it.

**Comment by elanhickler** [comment]
I mean don't worry about what I'm doing, just tell me how you'd do it in Chaosfly and I'll figure it out.

**Comment by elanhickler** [comment]
what if I triggered a resize somehow in the callback and did the hiding by not placing the slider?

**Comment by RobinSchmidt** [comment]
in chaosfly, we use buttons (which serve as "tabs"), and the visibility of some gui elements (not just sliders but whole sub-module editors like the env-generator editors) are made in/visible inside the buttonClicked callback. but the same strategy can be applied to a combobox as well. but if you get access violations because the sliders don't exist (yet?) it sounds to me like the callback gets called before the sliders are created. maybe i need to have a look at the actual code. when does the access violation occur? on construction time or on selecting a new option?

**Comment by elanhickler** [comment]
on loading the plugin

**Comment by RobinSchmidt** [comment]
then look at the call stack in the debugger. look at which function called the callback. was it before the sliders were created? was it in the constructor? if so, why?

**Comment by RobinSchmidt** [comment]
it sounds to me like the callback is triggered in the constructor before the sliders are created
