### ISSUE TITLE
antiAliasFilter is giving -nand

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#18]
![](https://puu.sh/w2kMk/682eefc714.png)

**Comment by elanhickler** [comment]
ill keep testing, not sure if it's happening after I reset the Spiral Generator.

**Comment by RobinSchmidt** [comment]
whoa! that's weird! what are the filter coefficients (a- and b- arrays)? what is the cutoff freq (i.e. subdivision)? how can i reproduce this?

**Comment by elanhickler** [comment]
you'll need my specific RS-MET code......... maybe tomorrow I will make a separate spiral generator repository and put my RS-MET code in there.

**Comment by elanhickler** [comment]
![](https://puu.sh/w2nBG/3d90acf0ef.png)

**Comment by RobinSchmidt** [comment]
that actually shouldn't make a difference (unless you edited the filter class). hmm - so it looks like the y2 value is already nan. i need to look at this tomorrow. maybe i forgot an initialization. i again notice that i should really switch to use std::vector instead of raw c-style arrays. then, we could look at the whole array in the debugger. ...these are things one only learns through experience. i don't want to use raw - c-arrays anymore. or juce::Array, for that matter. i say that, so don't have to make my mistakes again :-)

**Comment by elanhickler** [comment]
I know where the nan is coming from. It's coming from asin() where anything above 1 or below -1 results in NaN

**Comment by elanhickler** [comment]
got it. I debugging by doing a conditional break if tmp != tmp (which catches -nand)

Then I "went up stream" until I found the first occurance of a bad value (-inf and nand), and it lead me to a value in spiral generator.
