### ISSUE TITLE
Runtime error on Radar Generator due to bad .settings file and xml reading

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#198]
![image](https://user-images.githubusercontent.com/9116575/41117446-e5e539ce-6a41-11e8-9068-4a6b81b25ab5.png)

![image](https://user-images.githubusercontent.com/9116575/41117486-03d870c2-6a42-11e8-9fc2-7e1a7b7fc2ff.png)

I will need you to attempt to debug/run a standalone version of Radar Generator. Simply running Radar Generator causes this error (and Radar Generator simply doesn't work because of it).

**Comment by elanhickler** [comment]
solved by deleting file:
C:\Users\Elan\AppData\Roaming\Radar Generator\Radar Generator.settings

![image](https://user-images.githubusercontent.com/9116575/41118394-a86fabb2-6a44-11e8-8f19-35b3c961a043.png)

from file: JUCE\modules\juce_data_structures\app_properties\juce_ApplicationProperties.cpp

**Comment by elanhickler** [comment]
the problem is not solved!

![image](https://user-images.githubusercontent.com/9116575/41134459-4466c5fa-6a81-11e8-9b92-55a4b81cf265.png)

Maybe it's a general issue of getting a null xml, wtf?

**Comment by RobinSchmidt** [comment]
can i just pull in your latest soundemote repo and build it? if the xml is a nullptr...hmm...that's weird - looks perhaps as if the host passes invalid data in a state recall? dunno. of course, i could check against a nullptr and bypass the code if it is null indeed. ...but actually, the xml shouldn't be a nullptr in the first place. if it is, it could be because the state-recall data passed by host somehow doesn't really translate well to an xml, i.e. is invalid

**Comment by elanhickler** [comment]
I figured out the problem, it's because the xml was invalid. There were spaces where there shouldn't be spaces due to using spaces in the audio module name.

**Comment by RobinSchmidt** [comment]
ah - ok.
