### ISSUE TITLE
Add custom mosue handling to rs widgets

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#285]
I need to skin your EQ and breakpoint envelope modulator, I need this so I can use ciruclar knob style mouse handling.

for reference this is the mosue handling code I use knobs.
```cpp
void mouseDrag(const MouseEvent& e) override
{
  double scale = .003;

  if (ModifierKeys::getCurrentModifiers().isShiftDown())
    scale *= 0.0625;

  if (!isEnabled())
    return;

  if (!e.mods.isRightButtonDown() && !e.mods.isCommandDown())
  {
    int newDragDistance = e.getDistanceFromDragStartY() - e.getDistanceFromDragStartX();

    int dragDelta = newDragDistance - oldDragDistance;
    oldDragDistance = newDragDistance;
    dragValue += scale * dragDelta;

    double y = normalizedValueOnMouseDown;
    y -= dragValue;
    y = clip(y, 0.0, 1.0);

    setNormalizedValue(y);
  }
}
```

**Comment by RobinSchmidt** [comment]
hmm - ok - that means, you need me to allow you to set the painters for the editors - like providing an Editor::setSliderPainter, setButtonPainter, etc. that sets the painter for all its internal widgets. and then you need a similar mechanism for the mouse-handling - like RSlider::setMouseHandler and then also Editor::setSliderMouseHandler? or something?

**Comment by elanhickler** [comment]
why would I need to set the editor mouse handler? I can just override mouse handling.

Maybe this should be a quick fix. The only reason I need to skin EQ and Breakpoint is because they have complex code for handling adding/removing/editing points.

For future projects it would be better to use an EQ with a fixed number of points to allow for modulation. The only thing I will need to skin in the future is breakpoint.

**Comment by RobinSchmidt** [comment]
>  I can just override mouse handling.

you can override these things if you create subclasses of my widget classes and then use those subclasses in your editor (sub)classes. but when you use a ready-made editor from me, you cannot replace the widget class that i'm using there (....or wait - now that i think about it - it should be actually possible thanks to the fact that i'm using pointers instead of direct objects......but that would be quite laborious still - you'd have to delete all of my widgets and the create and add yours instead.)  ...but i guess, you don't want to do that, if instead, you just could just tell the editor which mouse-handlers it should use

**Comment by elanhickler** [comment]
I could try the deletion thing.

**Comment by RobinSchmidt** [comment]
why would you want to go through that pain? it will bloat your code size, increase your initialization time - because the unused objects would still be constructed only to be immediately deleted and you would have to more or less replicate my widget creation code. you would "undo" my widget creation only to then to "redo" almost the same thing with your own widgets. you would still have to also subclass my editor class to do that. and: it doesn't work with recursively nested sub-editors....well...unless you apply the same scheme to all sub-editors and subsub-editors. i currently think, factoring out mouse-handling into a mouse-handler class is the better design. but maybe i should think about it more

**Comment by elanhickler** [comment]
no longer relevant / solved
