### ISSUE TITLE
discussion: Creating VST3 plugins

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#287]
Where in the code do you register VST2 host parameters?

registering VST3 host parameters is a matter of providing a range, a unit display, and the type of control (integer, float, boolean, choice) which means it's easier to use the parameter in the DAW because it reflects the state much better.

**Comment by RobinSchmidt** [comment]
it's in `AudioPlugin::createHostAutomatableParameters`. it creates a bunch of objects of type `jura::AudioPluginParameter` which is a subclass of both `juce::AudioProcessorParameter` and jura::MetaParameter. this class glues together (by multiple inheritance) our meta-parameter-system with juce's host automation wrapper

**Comment by RobinSchmidt** [comment]
our meta-parameters are actually all just continuous, normalized parameters - because of this additional indirection, it doesn't really seem to make sense to talk about units, ranges and type

**Comment by RobinSchmidt** [comment]
hwy do you actually want that? so you want to make a plugin with *fixed* automatable parameters without going through our meta-parameter system?

**Comment by RobinSchmidt** [comment]
yes - unfortunately. i think, that's really a bad thing for the community and shows how bad it is to depend on a sdk that is tightly controlled by some company. however, we are actually not directly dealing with any of that plugin-sdk stuff because it is abstracted by juce. i guess, if you want to use additional features of the vst3 parameter handling, you may call some of the inherited setup functions on the AudioPluginParameter objects right after their construction. but as said - that would make sense only if we would have hard-wired automatable parameters - but ours are "soft-wired", ...if that is a word

**Comment by RobinSchmidt** [comment]
> call some of the inherited setup functions 

or - wait - no - it doesn't actually have setup functions:

https://docs.juce.com/master/classAudioProcessorParameter.html

...i expected things like setRange, setUnit, etc. - but apparently, that is supposed to be handled by overriding getText and so on.
