### ISSUE TITLE
What do you recommend for music processing for visualizers?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#290]
I need to start experimenting with transient detection, extracting musical parts like the kick or snare or hat, going into envelope following or ADSR to control various parameters of a visualizer.

Need:

1. bandpass filter for extracting a frequency band to then go into an envelope follower and then possibly a gate (I guess that's what a transient detector is?). What bandpass filter do you recommend? What about the one made for the multiband compressor? Or what 
2. Envelope follower (you already made a few designs I can use)

What else do you think I need or do you have additional ideas? I may have a client that needs this as well so I want to be prepared for that.

**Comment by RobinSchmidt** [comment]
1. i would think, the type of bandpass is perhaps not that critical. i'd probably try butterworth first. the one for the multiband compressor has rather shallow slope (6 dB/oct) - you probably want some more. and you don't need perfect reconstruction in this case (or in fact, any reconstruction at all)

2. yes, probabably one of the simpler designs will be sufficient here as well, since you don't really care about the quality (smoothness) of the envelope. you just want to avoid false triggers which is a far less demanding requirement

that said - i would say, for this application, something based on the spl-style differential-envelope algorithm could be useful for this. and/or - if you can tolerate some latency, a block-based FFT algo....like a realtime version of rsOnsetDetector (you'd get a latency equal to the blocksize)

**Comment by RobinSchmidt** [comment]
are you talking about visualizers like winamp avs or milkdrop? i always found them quite amazing from an artistic point of view - the only problem was (at the time i last checked - which is long ago) that they never really felt "in-sync" with the music - which is shame

**Comment by elanhickler** [comment]
Yeah, so I'm not talking about visualizers like winamp. I have some ideas to turn oscilloscope / prettyscope into something that responds to music. Just take any synth, give it music as an input, have the music processors output to the synth's frequency or other parameters.

For example, set the synth to 0 frequency and let the music processor control frequency with an envelope follower. Now you have a pattern on the oscilloscope that appears and disappears on beat, or maybe it draws itself slowly for each beat, or maybe the shape evovles over time, or maybe the shape is drawn forwards and backwards (if you have bipolar frequency modulation).

**Comment by elanhickler** [comment]
no longer relevant / old discussion
