### ISSUE TITLE
please add "preset version" in your framework

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#31]
there's a few things this would be useful for.

It might be nice to also have an optional extension other than xml, somethign custom like .sgpreset for spiral generator preset

**Comment by RobinSchmidt** [comment]
i already have something like that in place. look at the comments in AudioModule::convertXmlStateIfNecessary (in .h and .cpp file)

**Comment by RobinSchmidt** [comment]
for custom file extensions, i think, you could override StateFileManager::loadFile/saveToFile. i actully like the xml-extension - because when i double-click on a preset file, i gets opened in an appropriate text-editor. with custom extensions, windows would not know, which app to use to inspect the file

**Comment by RobinSchmidt** [comment]
or, maybe you could just set the member variables defaultExtension, wildcardPatterns (inherited from FileManager). i'm not sure. maybe try it

**Comment by RobinSchmidt** [comment]
...but some more technical end users also tend to appreciate a transparent, human readable preset format. well, at least, i once received some kudos for using plain xml.

**Comment by elanhickler** [comment]
oh, then a .sgp.xml might be ok... ill think about it.

**Comment by elanhickler** [comment]
oh I didn't make it clear, I was hoping for a preset version to be stored with the preset inside the xml.
