### ISSUE TITLE
RS_DEBUG_BREAK causes crash in non-debug builds

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#316]
This is crashing my release builds. Please ensure this macro only exists on debug builds.

`F:\(PROGRAMMING)\RS-MET\Libraries\RobsJuceModules\rapt\Basics\DebugTools.h`

Line 30

I am commenting it out for now on my side.

**Comment by RobinSchmidt** [comment]
oh! apparently your code triggers rsError to be called from somewhere which indicates that something went wrong. i suppose just uncommenting the debug-break will not fix the underlying issue but rather have it go unnoticed (and perhaps cause other problems later on). but it's weird when rsError gets triggered only in a release build. i also write an error message to the console there (if there is one). i would recommend to try to figure out why rsError is getting called in the first place

**Comment by RobinSchmidt** [comment]
...on the other....the original intention for this rsAssert thing was that it is supposed to be optimized away in release builds. that probably stopped working since i added printing the error message. formerly, the debug-break only content of the rsError function - and that macro is supposed to resolve to "empty" unless we are in a debug-build.....i think, i need or ifdefs to make that work again. ...on the other hand, it could actually a good thing that the error detection fired here. because if it does, something is wrong...hmmm...

**Comment by RobinSchmidt** [comment]
> Please ensure this macro only exists on debug builds.

actually, that should be the case:

```cpp
#if defined(DEBUG) || defined(_DEBUG)
  #define RS_DEBUG
  #define RS_ASSERT(expression) { if (! (expression)) RS_DEBUG_BREAK }
  #ifdef _MSC_VER
    #pragma intrinsic (__debugbreak)
    #define RS_DEBUG_BREAK __debugbreak();
  #else
    #define RS_DEBUG_BREAK __builtin_trap();  // preliminary - gcc only
  #endif
#else
  #define RS_DEBUG_BREAK { }
  #define RS_ASSERT(expression) { }
#endif
```

the DEBUG or _DEBUG macros are supposed to be defined only in debug builds. and if they are not defined, RS_DEBUG_BREAK resolves to empty. ...that's the intention, at least

**Comment by elanhickler** [comment]
I think I was wrong and that I was running a debug build at the time. Will close for now.
