### ISSUE TITLE
slider sets value twice, and second time is wrong, breaking bug

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#35]
https://puu.sh/wf1bF/b29cef2daa.mp4 (download to desktop, this one didn't play in my web browser)

For this specific value of 10, the slider sends a value twice. Once it is 10.00000000, another time it is 9.999999 which then becomes 9.

Other times it will simply send 9.0000000 twice which does not create a problem, but still strange. The breakpoint is hit twice every time.

**Comment by elanhickler** [comment]
this is a breaking bug because loading the patch will give you the incorrect value the same way.

currently it's impossible to save a patch with x4 tempo setting (value of 10). It will load as x3 (value of 9)

**Comment by RobinSchmidt** [comment]
downloaded it, but somehow the file seems corrupted (it shows a gray screen with some artifacts from the original video)....but: this could to be related to the combobox-bug we had last time, i.e. the conversion to float (for automation) and then sending the value back from the host to the plugin. can you try to give the underlying parameter object a nonzero "interval" value in the constructor? like, when your slider shows 3 digits after the decimal point, give the parameter an interval of 0.001, such that all values are rounded to 3 digits - or whatever is appropriate. with a zero-value, there's no rounding whatsoever and that may play not so nicely with the double/float conversions (when values are later rounded to int)

**Comment by elanhickler** [comment]
i have interval set to 1.0

**Comment by RobinSchmidt** [comment]
hmmm...weird. i can't watch your video - can you give me instructions to reproduce it?

**Comment by elanhickler** [comment]
1. enable an lfo
2. set rate mode to tempo
3. set value to x3
4. put a breakpoint on `void setLFOTempo(int lfoindex, double x)` SpiralGeneratorCore.h line 64
5. click the slider a little bit forward so it gets set to 4. The breakpoint won't be triggered until a new value is set if you carefully click moving your mouse forward a few pixels at a time until you get to the next value. Basically, just get to x4.

You will see that x is 10, then if you continue debugger, the breakpoint is hit again and it is 9.99999

**Comment by elanhickler** [comment]
here's another video: https://puu.sh/wfrPL/c102136824.mp4

**Comment by RobinSchmidt** [comment]
ok - update my library and try again. i just noticed that there actually was no quantization code yet in the parameter class. i added it. you should now get two calls with the correct value (10). that you get two calls is because the 1st call comes directly from the slider and the 2nd comes from the roundtrip through the host-automation system. i currently have no idea how to avoid it. maybe must think about it

**Comment by RobinSchmidt** [comment]
> edit: seems like the breakpoint isn't always hit twice. first time in the video (value 10) was only once.

this could probably mean that sometimes the double/float conversion actually changes the final value and sometimes it doesn't. i.e. values that are precisely represented as float are not set twice, because the comparison, if the newValue == oldValue is true in this case - so there's nothing to do. but when the float is slightly off from the double, it is set...or something. i didn't verify this, but this is my hunch

**Comment by RobinSchmidt** [comment]
...but wait...it is hit one time and the other time it isn't with the SAME value...now, that's strange

**Comment by elanhickler** [comment]
that is correct

**Comment by elanhickler** [comment]
your latest commit fixes the issue, but the breakpoint is still getting hit twice.

**Comment by RobinSchmidt** [comment]
yes - the only way i currently see to avoid this would be to add a check
`if(value = newValue)  return;` to Parameter::setValue....but that seems to break total recall...hmm

**Comment by RobinSchmidt** [comment]
ha! of course that doesn't work! it should be `if(value == newValue) return;` ...need to try again...
