### ISSUE TITLE
JURA PhaseScope CPU spike issue

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#54]
In the future I'd like to use PhaseScope visualizer in some of my synthesizer plugins where I need to have a fallback if OpenGL isn't supported.

After some time using PhaseScope, CPU usage spikes to 100% and remains there until you reset the plugin. I don't need this to be fixed any time soon, but I figured I should remind you of this issue.

**Comment by RobinSchmidt** [comment]
ok. could perhaps be a denormal issue in the pixel decay filter.

**Comment by RobinSchmidt** [comment]
maybe i should somewhere use this in my framework:
https://en.wikipedia.org/wiki/Denormal_number#Disabling_denormal_floats_at_the_code_level

**Comment by elanhickler** [comment]
Sorry for saying you should throw your phase scope code in the trash that I paid a good amount of money for. I'd like to keep this project going, actually, as an alternative to PrettyScope.

Could you fix the CPU usage pike problem? I want to have a phase scope for my audio plugins.

**Comment by RobinSchmidt** [comment]
i would not throw anything in the trash, that i invested a good deal of work and thought in, anyway. no matter, if i did this on my own accord or in the context of contract work. who knows, what it's good for at some point. i'm pretty sure, it's a denormal issue. i'll look into it. i have precautions against that in all of my rosic library - you see that i add `TINY` in lots of places (iir filters mostly). i think, i should do that there, too. or maybe i can find a better fix based on cpu switches

btw. phasescope can still serve as a good prototype for anything you do in prettyscope. you can do anything in plain c++ instead of having to deal with the additional complexities of the OpenGL shader-language

**Comment by elanhickler** [comment]
I think Gaussian filter has a similar CPU issue

**Comment by RobinSchmidt** [comment]
damn...yeah ...that's 99% sure that pesky denormal thing. i hoped, cpu manufacturers would have sorted that out meanwhile. apparently not :-(

**Comment by elanhickler** [comment]
pleeez fix, I want to have a CPU-based oscilloscope for mushroom generator

**Comment by RobinSchmidt** [comment]
ok, i have tried setting this (in AudioPlugin::processBlock):

https://software.intel.com/en-us/node/523328

but didn't test yet because i didn't see this behavior over here (but i've not really been measuring performance anyway as i'm testing with debug builds). does/did it occur in both 32 and 64 bit builds?

**Comment by elanhickler** [comment]
Jim was just saying something about that, how he fixed denormal issues with it. I'll test.

**Comment by RobinSchmidt** [comment]
ok, it would probably a good idea to set it back to its original state, before processBlock returns, but i don't know how. it's probably not an issue in practice but good style

**Comment by elanhickler** [comment]
I dunno about 32-bit yet, but definitely works for 64-bit

**Comment by RobinSchmidt** [comment]
ok, that's good news!
