### ISSUE TITLE
Standalone version of Chainer

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#56]
Can your chainer be made standalone/executable?

Also, can we have PrettyScope as a chainer module? I'd like to have a standalone prettyscope, and figured I could make it a chainer module to make that happen.

**Comment by RobinSchmidt** [comment]
i think, it should be possible. it should be a matter of setting up the .jucer file appropriately. as prettyscope is a subclass of AudioModule, it should be possible to integrate it into chainer. chainer accepts any subclass of AudioModule as module. ....but then, you would do that in your fork, right?

**Comment by elanhickler** [comment]
I'm trying to cater to your framework and your design intentions.

Are you saying PrettyScope would have to be a free product and implemented in your library? Or I have to create a fork? If I create a fork then won't it be more difficult to stay in sync with your library?

Also, this same issue will come up for all my commercial products.

**Comment by RobinSchmidt** [comment]
if your eventual goal is to have a standalone version of prettyscope, then you don't need chainer at all. i think, juce supports "standalone" as one of its "plugin" export formats. you can have vst, au, etc and also standalone.

if chainer is to be a free product and prettyscope is part of it, well, yes, that would maker it available for free too unless you build a custom version of chainer that includes prettyscope. that's why i was mentioning using a fork. how else could it work - unless my chainer itself supports plugins (which it currently doesn't)

**Comment by RobinSchmidt** [comment]
keeping a fork in sync is probably messy indeed

**Comment by elanhickler** [comment]
Well, I'd like all my products to benefit from the anything-to-anything modulation system and macro controls you will be doing.

I'll even go ahead and use your design paradigm of "user must explicity set controls to be available to host modulation"

**Comment by RobinSchmidt** [comment]
i will use chainer as my context to develop the modulation system, but it should be re-usable in other products, too

**Comment by elanhickler** [comment]
So then I'm a bit confused, I don't see the big picture.

I think I need to start an audio plugin project from scratch, like, you should give me one solid starter project to use. I'll definitely do that for Spiral Generator and the oscilloscope music synthesizer series.

**Comment by elanhickler** [comment]
no longer relevant
