### ISSUE TITLE
Why is numCycles an int for screenScanner?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#60]
Can't we do partial cycle numbers? 1.5 cycles (zoom out) , 0.5 cycles (zoom in)

**Comment by elanhickler** [comment]
also i need a phase offset variable to "move the waveform left or right"

also, if you do an inc() offset variable (like you increment the phase +/- some amount extra) won't that create the "propogating waveform" effect?

**Comment by RobinSchmidt** [comment]
> Can't we do partial cycle numbers

because this maps to an internal algorithm parameter which is intrinsically integer: namely, the number of upward zero-crossings that i count before resetting the sawtooth phase. i have no idea how i would count to 3.7 cycles, say. i think, zoom has to be done via the ScaleX parameter

> also i need a phase offset variable to "move the waveform left or right"

ok, well - as said this calls either for a delayline on the scanner's input signal or i must somehow delay the phase reset inside the scanner. i need to think about, what's the best thing to do here

> also, if you do an inc() offset variable (like you increment the phase +/- some amount extra) won't that create the "propogating waveform" effect?

i think, it would, as long as you are modulating it into one direction

**Comment by elanhickler** [comment]
what you are saying makes no sense. It's just a phasor controlled by a frequency detector. I'll see if I can mess with the code myself, I think you are way over-complicating this.

**Comment by RobinSchmidt** [comment]
no, it isn't. that's what it was before and what didn't work well

**Comment by elanhickler** [comment]
oh..............
