### ISSUE TITLE
Crash / Infinite Hang if setting sigmoid clip to 0

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#63]
ChaosGeneratorCore.cpp
![image](https://user-images.githubusercontent.com/9116575/29741792-168b3434-8a28-11e7-8dbc-8a7a0caab955.png)

I had to put in a minimum value of 0.001. I tried 0.000001, but there was still an infinite hang.

**Comment by RobinSchmidt** [comment]
i'm getting build errors:

```
Cannot open source file: '..\..\JuceLibraryCode\rapt.cpp': No such file or directory
Cannot open source file: '..\..\JuceLibraryCode\romos.cpp': No such file or directory
Cannot open source file: '..\..\JuceLibraryCode\rosic.cpp': No such file or directory
```

did you re-organize the directory structure and/or change compile include-path settings?

anyway, that smells a lot like a division-by-(almost)zero error. in the documentation of `ScaledAndShiftedSigmoid::setWidth`, ist says: newWidth should be > 0. because if it is indeed zero, there's a division-by-zero somewhere in the formulas. it seems, we need a little bit of margin to zero for numerical precision reasons - i suppose, we get some ridiculously large value somewhere. is this margin a problem to be addressed or is your solution with the max-function good enough?

**Comment by RobinSchmidt** [comment]
i just changed `ScaledAndShiftedSigmoid<T>::updateCoeffs()` so as to hopefully avoid the precision loss. it should hopefully be numerically better behaved now. but i couldn't test yet for lack of compilable context, so i'm not sure, if i got the math right. it's actually simple, but stupid mistakes are stupid. can you try with the new version?

**Comment by RobinSchmidt** [comment]
> avoid the precision loss

in the old version, when `width` was small, i was subtracting two very close floating point numbers - an operation known to cause precision loss. but in this case, it could be avoided because the width itself is the full-precision difference. so, the new formulas are supposed to be algebraically equivalent, but numerically better (and actually also more efficient)

**Comment by RobinSchmidt** [comment]
> an operation known to cause precision loss

consider:
```
   3.14159
  -3.14157
-------------
= 0.0002
```

the arguments of the subtraction have 6 significant figures whereas the result ha only 1. this is how the precision loss in the subtraction of two close floating point number occurs

**Comment by elanhickler** [comment]
uhh, you fixed the issue? I just removed my std limits and it still crashes.

btw, you have to probably need to build a new project with JUCE if the VS project is not tracked on git.

**Comment by RobinSchmidt** [comment]
yes - regenerating the project with the jucer fixed the build issue.

it's still illegal to pass a 0 value, but a potential precision-loss issue for values close to zero, like 0.00001 should now be better behaved. if you pass 0, you'll get some inf and nan values in the internal coeffs of the ScaledAndShiftedSigmoid object.

**Comment by elanhickler** [comment]
k. btw, still waiting for you to respond about doing a "double click on oscilloscope to run an action", i.e. when the GUI is hidden, double click will show GUI. Actually, might as well allow double click to show/hide gui. I also want to add a GUI button to hide GUI... which will probably be easy to do once I get the double click working.

**Comment by RobinSchmidt** [comment]
btw. i'd recommend to - instead of using max - just set the minimum value of the clip parameters to something like 0.001. then, the gui is more honest, i.e. it does exactly what it says it does.
