### ISSUE TITLE
using se_framework module for jucer, why does it disable all cpp?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#71]
![image](https://user-images.githubusercontent.com/9116575/30043897-26dd4244-91af-11e7-9b11-ebfb2005beec.png)

wtf? What's the point of this?
PrettyScope fails to build because myparams is disabled. (I know how to enable it at least)

**Comment by RobinSchmidt** [comment]
for juce modules, the projucer by default set these files to "not build" because these cpp files are assumed to be included in se_framework.cpp. this cpp file is the compilation unit for that module. the point of modules is to almalgamate all the cpp files into a single compilation unit. this greatly reduces the build time. you should have tried building juce 10 years agao when it was not yet organized in modules. each cpp file is compiled on its own. that takes ages

**Comment by elanhickler** [comment]
How do I solve this?... hey, but se_framework.cpp is disabled too!

**Comment by RobinSchmidt** [comment]
yes, but i think it is included a corresponding cpp file in the JuceLibraryCode folder - and *that* file is built. the build system with juce is a bit peculiar. there are probably good reasons but it's something one must to get used to....and always use the projucer

**Comment by RobinSchmidt** [comment]
so yeah - you still need to include the cpp file into your se_framework module cpp file

**Comment by elanhickler** [comment]
WORKS!
