### ISSUE TITLE
When using Ctrl + Drag fine tune, value jumps to mouse position.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#9]
Value should not jump to mouse position when performing fine tune.

**Comment by elanhickler** [comment]
Actually the issue might be that when performing fine tune i.e. ctrl + click + drag, the ctrl + click initiates "reset to default value"

**Comment by RobinSchmidt** [comment]
i changed the slider behavior now. it jumps to the new value only when alt is pressed, fine-tuning is done via shift. i'm not sure, if this behavior is better now. it feels weird to me, but maybe it's a matter of getting used to it

**Comment by elanhickler** [comment]
you could always do "slider jumps to mouse unless alt is held" basically the opposite.

**Comment by elanhickler** [comment]
another thing you could do

shift + drag = coarse tune
shift + ctrl + drag = fine tune
ctrl + click = reset
click = jump to mouse

**Comment by elanhickler** [comment]
bug: dragging with mouse, then holding shift to fine tune (while still holding mouse button down) causes value to jump.

**Comment by elanhickler** [comment]
oh, click cannot be "jump to mouse" otherwise double-click would set the value before you can do a "type in value" the way you have it right now is perfect then.

What are the mouse modifiers for mac?

**Comment by RobinSchmidt** [comment]
> What are the mouse modifiers for mac?

i think, ctrl is replaced by some mac-specific "command" button - or whatever it is called. shift and alt should be the same.

> bug: dragging with mouse, then holding shift to fine tune (while still holding mouse button down) causes value to jump.

yeah -  i know. it's not exactly a bug but a consequence of the implementation. i check for the shift-modifier inside the mouseDrag callback. the only thing i have available about the former value of the slider is the value at mouseDown. i currently don't see any convenient way to keep track of the whole dragging history. so basically, what happens is: when you press shift during dragging, it jumps to the value where it would land, if you would have pressed shift since the start of the dragging action. i don't know how to solve this. maybe i need to think harder

**Comment by elanhickler** [comment]
you can't get the current value when user hits shift while dragging, make that the new "starter" value. You essentially end the current drag of click, and enter a new drag of shift-click, no need to keep track of drag history.

**Comment by RobinSchmidt** [comment]
yes. i only need the most recent x-position in the drag callback and could update it there. i must think about the details. i guess, i need a state-variable for this. in juce itself, i can only inquire getDistanceFromDragStartX which is what i currently use. i may have to keep track of the "dragDistance" myself, or something

**Comment by elanhickler** [comment]
make sure to account for the user holding shift, then not holding shift, then holding it again

**Comment by RobinSchmidt** [comment]
i think, it works now

**Comment by elanhickler** [comment]
wait, you only just solved this? I thought you solved this a while ago! waaaat.

**Comment by RobinSchmidt** [comment]
i thought so too, haha!
